name: CI Tests

on: [push, pull_request]

jobs:
  ci-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        OS_TYPE: ["centos"]
        OS_VERSION: [7, 8]
        OSG_VERSION: [3.5, 3.6]
        