name: Test tarball builds

on: [push, pull_request]

jobs:
  test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        OS_TYPE: ["almalinux"]
        OS_VERSION: [8, 9]
        OSG_VERSION: [3.6.123456, 23.123456]
    env:
      OS_TYPE: ${{ matrix.OS_TYPE }}
      OS_VERSION: ${{ matrix.OS_VERSION }}
      OSG_VERSION: ${{ matrix.OSG_VERSION }}
    steps:
      - uses: actions/checkout@v3
      - name: Run Test Script
        run:
          sh tests/setup_tests.sh ${OS_VERSION}
